sudo: false
language: node_js
before_script: make
script: make test
env:
  global:
  - SAUCE_USERNAME=atma
  - SAUCE_ACCESS_KEY=fb6b87b9-e1a2-4af6-9326-78caf15eeb43
  - secure: iR7F0XOIdgWNxiRi0TT/jaHQhv7J5hN/SrUb8nig2xNd28g0Pf7vnIso6R9gEEpiD+4ErT7GeD8RBrnMCkLsVqRZmzhoaMTQQeV5UxOurawkp3KKjjt1lys77Q4vzez2i/0Jm+gWkXgXT+PdzkfpJtIkpGC7WRMYHrwxAaiU0mxWayUpEZhY0aRpP33oXx4DFere0F7M+A0ohTiQQcNy6baf59TZp/T2x3/85l9l7ycigxrBpFm0s1jDx08h2SBS0NPBwHxo7AIo3fUH9qsNDVO0+jArJBeWr2CeX3ag5gdajp84QjYgGwq8VG6HGDp4oVdPuDrUBEDAKmFxMj/uB+/gnA9wAYihD7Ih7AZyQ8Pss9C+g5p9pP72i8Sg1rbXCN7YdSOsBrw3E4BZD5jEDrjTFtOqxkn7r3thl8FVuvn6bHtbMv6GDBUhOhhcZRkPZE0yCjmN2WWPqpsSJJzuZX3hDRoJcbM7ZYUDXpZb8m7QtdbrW00vzbS0a1CT3Wtgyvo150V0zbo0uJZa3eelBPxhlPqDTHnFJQIoOWUAZxj7PMyX2J5bLF7+gs5L2RvELrsCeldrPb44Q0m2b8PIgy8zT+7m24RX07Yjj9ze5gBO94VfsRUKrZSQIpujkQggAPeh3KUJEUPX0++OII7xcvSgdbHKbaKsD/GVsRoNwrc=
  - secure: JhER12vRCBpZgUNqlDTWanDxPICivbhpu4s46ewWX6MaSZUqFJj4vZQ/rRC9hHeIaXD2ukRG3RnO+u1EKqmgh46HzSJ6P7rJP1LTOhmCJsbtCUpgkBnDeDFrZtvGe0Y/mJyanTlvPtregmqO6+y9BgHJ+Gxo/05LM2awe/6fSQbUNWLcQK3pFrWcoOKxpDPmTV0yP6hgltIxXNrkzGVoe1NWd7t1K3GWttaCb9937HRsu69BXWqmEIhwQbaQ+XydGgtcffQvGS0lhT3IJ9mt8aNIOdMZanTrsFaRWty0p8sokDpMqg9B72efLz+r2DHV1EvYa9joboygwKC5cVVhi/lZS/CO0fnxdWRJqUDUoZaOc3kBTK/kpg0y5dM3DK9oazkXoztU4Y+9Sbmx+0pGmiy0DNTpMrbSybqeyixPP7qHn+9/UNQ/0flJArjFbTvJy5No/dOhAzEsPnkAv9MItbF0jyUnKhb2WqUf/i+qkNPPI/bad2ULxw+WC1+cPWWEdywdfP5Z8cJs9SXOZbx0mJMWepHtYVxPPSGLicaHLv071F9m0RrMKtCUJg1EDtqHLSSJJVln/QoYIWJT1XbAq/Stx6dE0+FGrYXqFPulj7qaF42G8E9R2ykdC7bzYWciSn+B4lyuNMe+HY67RDdYVXdKFRDSVqDD0s0PA+lbjEw=
  matrix:
  - PHANTOMJS=1
  - SAUCE_PLATFORM="Windows 7" SAUCE_BROWSER="googlechrome" SAUCE_VERSION=""
  - SAUCE_PLATFORM="Windows 7" SAUCE_BROWSER="internet explorer" SAUCE_VERSION="11"
  - SAUCE_PLATFORM="Windows 7" SAUCE_BROWSER="internet explorer" SAUCE_VERSION="10"
  - SAUCE_PLATFORM="Windows 7" SAUCE_BROWSER="internet explorer" SAUCE_VERSION="9"
  - SAUCE_PLATFORM="Windows 7" SAUCE_BROWSER="internet explorer" SAUCE_VERSION="8"
addons:
  sauce_connect: true
deploy:
  provider: npm
  email: atma@atmaworks.com
  api_key:
    secure: MG8w7ttp41GDbfFtourttuwxRJayPThgTIzRQ/TjOpJuKZ3hhqz3xA4OVDGpBCYOUNMVXrFdEwCymTYYKhfXNXp1hmzfpJKKTpPhqSRr3X8tTgWDECBfvqB9iT1k6MnCIj1YdVRcxyhavjAulCbHbJUQVBy6j7xXtmFs1e9zwMQm8LxFir2Gkwi5KCCo9LMjlYj6ido1BLrUN/i/8hRHdfODXORgiYk3O1jb7GldtG9CFZvnYnkEitlRSOZNiMXKWLM3AyFRNJ3bETHAFbGT6yklkwno5N4pYGLMguq/y4EUmy0WLSE5gYy4ztIH2NfcLaiRDpozS6sN65HEusqzENhTvx9YLR5AutdlI1J3hXfDG3zNpHmdJ4I2h44/T4NagY4acdC/YLRhvUeK/SQWN3PgBzD/yQuSPjHUpwoRc8E0WONboPEsw9eeKPgkWjHOlF56YgbAX4BU5ZpikL+L/yW4LjmSzxDlZ2gKYaVdIWIHcFkEp8xqoUWUS+n4PU6Re+YPYsuww+aDA3z8CFdDWnGaIsyYcONiLzGAov+rszHuJrTXSJ0l0YS7UpZPpD5Bc4iGki+M8aO4wdeYNqJcsxWqifp0RsXbY8wRtfvFqcbK4t3IHFRQLKjWojWjh+UrfboLws76rKMeY4SQ3FE1SpTCnNrfpgBtKfpkIs1IDH4=
  on:
    tags: true
    repo: atma/fetch-compat
