#!/bin/bash

set -e

port=8080

# Spin a test server in the background
node ./script/server $port &>/dev/null &
server_pid=$!
trap "kill $server_pid" INT EXIT

if [ "$SAUCE_BROWSER" == "internet explorer" ] && [ "$SAUCE_VERSION" -eq "8" ]; then
  job=$(./script/saucelabs-start "http://localhost:$port/test/test-ie8.html")
else
  job=$(./script/saucelabs-start "http://localhost:$port/test/test.html")
fi

while true
do
  result=$(echo "$job" | ./script/saucelabs-status)
  [[ $result == *"\"completed\": true"* ]] && break
  sleep 1
  echo -n "."
done

echo -n ""

echo "$result" | ./script/saucelabs-result
